### ISSUE TITLE
Add package

### ISSUE THREAD

**Issue by asd617140123** [rockchip-linux/buildroot#29]
Hi 
目前想要在 buildroot 裡面加 一個 執行黨
在 buildroot/output/rockchip_rk3399/target/usr/bin
裡有看到 hello app 可是開機後再 usr/bin 裡面找不到檔案
請問有加 app 的流程嗎?

**Comment by JeffyCN** [comment]
you can simply put it in the board overlay dir.

and guessing you were seeing the recovery rootfs at that time, which should be:
buildroot/output/rockchip_rk3399_recovery/target
