### ISSUE TITLE
RK3188 Support ?

### ISSUE THREAD

**Issue by hardiksingh-rathore** [rockchip-linux/buildroot#3]
Is this buildroot having support for RK3188 ?

**Comment by KevanLan** [comment]
Yes.
You can refer to rk3399 config.

**Comment by worldomkar** [comment]
> Yes.
> You can refer to rk3399 config.

So you meant rk3399 is latest 'Rockchip' configuration for rk3188 and up including arm and arm64?
Does this mean we can use rk3399 as a starting point for porting BSP for RK3188/DDR3L/MALI400MP4 devices (e.g. MK908) and it'll be able to boot?
