### ISSUE TITLE
QT5 Multimedia's qvideowidget will not respect other widget's always on top rules

### ISSUE THREAD

**Issue by kadirbeytorun** [rockchip-linux/buildroot#35]
Hello @JeffyCN , I am working with the most recent version of rk1808's sdk from rockchip-linux and using qt5.12 for my projects.

We are using QCamera and QVideoWidget classes for capturing and displaying our mipi camera (ov9281)

Everything is running smoothly overall, we can show our camera frames on Qvideowidget without draining cpu resources. Yet if I want to show another widget (for example QLabel) on top of all widgets with "Qt::WindowStaysOnTopHint" property, QVideoWidget will not respect it's always on top rule and frames will show on top of the widget.

Are you aware of this bug? Is there a solution you can recommend for this?

Also, I noticed the buildroot in rockchip-linux and the buildroot in your own account are different in many regards (for example in your buildroot qt5.15 is available, while here qt5.14 is the latest)

Could you shed some light on all these issues? (Btw sorry for disturbing you with everything, no one else from rockchip seems to care about these github repositories)

Best Regards

**Comment by JeffyCN** [comment]
the WindowStaysOnTopHint only works with window type(toplevel wayland surface) in current sdk.

w.setWindowFlags(Qt::Window | Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint);
