### ISSUE TITLE
clarification about branches

### ISSUE THREAD

**Issue by bschiett** [rockchip-linux/buildroot#7]
can the 2016 branch be merged into the 2018 branch and is the 2018 branch being actively developed? or is the active development branch 2016 ?

**Comment by rkchrome** [comment]
Yes, that will do in later..

**Comment by bschiett** [comment]
thanks, can you clarify what the current branch is that we should use for
rk3288? we need kernel header 4.10.x support.

**Comment by rkchrome** [comment]
2016.x branch for now, and kernel used the 4.14.x version.
